use_frameworks!

def import_pods
  pod 'OrangeLabel', :path => '../'
  pod 'SimpleLayout-Swift', :git => 'https://github.com/pisces/SimpleLayout.git'
end

target 'OrangeLabel_Example' do
  import_pods

  target 'OrangeLabel_Tests' do
    inherit! :search_paths

    
  end
end
